### PR TITLE
ETL - Color Mapping

### PR DESCRIPTION
**Pull request by Yun-Wu**

### CODE REVIEW

**Comment by Yun-Wu** [comment]
[#35](https://github.com/wildlife-dynamics/ecoscope-workflows/issues/35)

**Comment by cisaacstern** [comment]
@Yun-Wu and @walljcg I'm curious what you'd think about categorizing this task, as well as #36, under `tasks/preprocessing`?

Is there some sense that I'm missing in which "transformation" is different than "preprocessing?

**Comment by Yun-Wu** [comment]
I assumed that `preprocessing` is to preprocess some dataframe to prepare for certain analysis. Data `transformation` is more general and can be placed before or after the analysis. Happy to hear your thought too.

**Comment by cisaacstern** [comment]
> I assumed that preprocessing is to preprocess some dataframe to prepare for certain analysis. Data transformation is more general and can be placed before or after the analysis.

That makes sense! I think the word "transformation" in my mind is just quite generic and a bit overloaded (then again, so is "preprocessing" 🙃 )... so this clarification is helpful. I'm happy moving forward with this naming!

**Pull request merged**
