### PR TITLE
Polish subject and patrol workflow

### PR DESCRIPTION
**Pull request by Yun-Wu**
- **demo**
- **update filter**
- **remove title**
- **use salif**
- **update patrol filters**
- **base layer**
- **colormap**
- **event color map**
- **two digits**
- **update widget type**
- **update data**
- **line width**

### CODE REVIEW

**Comment by cisaacstern** [comment]
TYSM! I will take a closer look at the test failures shortly.

**Comment by Yun-Wu** [comment]
> TYSM! I will take a closer look at the test failures shortly.

Thank you Charles! Don't worry about this PR. It's mainly to create a quick and dirty branch for Alex to use for his demo and is not ready to review yet. I'll break it down to smaller pieces for you to review.

**Comment by cisaacstern** [comment]
@Yun-Wu this was superseded by #312, so we can close, correct?

**Comment by cisaacstern** [comment]
Adding `stale` label pending confirmation we can close this.

**Pull request closed without merging**
