### PR TITLE
Enforce PRs Linked with Issues

### LINKED ISSUE #288: Enforce PRs Linked with Issues

### PR DESCRIPTION
**Pull request by Yun-Wu**
Fix #288

### CODE REVIEW

**Review by cisaacstern — APPROVED** [review]
This is so cool!

Do you think we should also require that the linked issue has a description in its opening comment?

I note that CI is passing here because of being linked to #288, but that issue doesn't have a description in its opening comment: 

Screenshot 2024-10-06 at 10 54 47 AM

I don't have a very strong opinion on this, just wondering if that extra step may provide even more clarity.

**Comment by Yun-Wu** [comment]
> I note that CI is passing here because of being linked to #288, but that issue doesn't have a description in its opening comment:

Good question. I added this PR mainly for the PGAFF reporting purpose and we don't need descriptions there. I agree adding descriptions could make thing clearer but also want to minimize the extra overhead for developers. What do you think @walljcg and @atmorling ?

**Comment by walljcg** [comment]
Thanks @Yun-Wu for this! Yes, I think we should force a description! I might regret that at some point but will help us all I think. Would be great if we can enforce this behaviour across all ecoscope repos including the ecoscope-pgaff reop.

**Comment by atmorling** [comment]
I agree with @walljcg - I think we're all going to hate this at some point or another but being forced into actually documenting what I'm doing seems like the right idea :sweat_smile: 

Thanks @Yun-Wu for making this happen!

**Pull request merged**
